"""
Assignment No 3
Name - Abhishek Kusalkar
Batch - B2
Roll No - 35
Assignment Title : Generating The N Gram Model using NLTK

"""

from nltk import ngrams
from nltk.util import ngrams

#unigram model
n = 1
sentence = 'Your smile makes me smile Your laugh makes me laugh Your eyes are enchanting You make my thoughts seem daft Since the day I first laid eyes on you My feelings grew and grew In that first conversation my knees clicked and clacked And those butterflies flipped and flapped And as I spill these simple rhymes My mind goes over time and time I have a crush, a little teenage crush I dont know what to do, about this lovely little crush'
unigrams = ngrams(sentence.split(), n)

for item in unigrams:
    print(item)

    
#bigram model
n = 2
sentence = 'Your smile makes me smile Your laugh makes me laugh Your eyes are enchanting You make my thoughts seem daft Since the day I first laid eyes on you My feelings grew and grew In that first conversation my knees clicked and clacked And those butterflies flipped and flapped And as I spill these simple rhymes My mind goes over time and time I have a crush, a little teenage crush I dont know what to do, about this lovely little crush'
unigrams = ngrams(sentence.split(), n)

for item in unigrams:
    print(item)


#trigram model
n = 3
sentence = 'Your smile makes me smile Your laugh makes me laugh Your eyes are enchanting You make my thoughts seem daft Since the day I first laid eyes on you My feelings grew and grew In that first conversation my knees clicked and clacked And those butterflies flipped and flapped And as I spill these simple rhymes My mind goes over time and time I have a crush, a little teenage crush I dont know what to do, about this lovely little crush'
unigrams = ngrams(sentence.split(), n)

for item in unigrams:
    print(item)


#using text file input

from nltk import ngrams
file = open("/home/exam/Awesome-NLP/Num.txt")
for i in file.readlines():
    cumulative = i
    sentences = i.split(".")
    counter = 0
    for sentence in sentences:
        print("For sentence", counter + 1, ", trigrams are: ")
        trigrams = ngrams(sentence.split(" "), 3)
        for grams in trigrams:
            print(grams)
        counter += 1
        print()

# OUTPUT -

"""
('Your',)
('smile',)
('makes',)
('me',)
('smile',)
('Your',)
('laugh',)
('makes',)
('me',)
('laugh',)
('Your',)
('eyes',)
('are',)
('enchanting',)
('You',)
('make',)
('my',)
('thoughts',)
('seem',)
('daft',)
('Since',)
('the',)
('day',)
('I',)
('first',)
('laid',)
('eyes',)
('on',)
('you',)
('My',)
('feelings',)
('grew',)
('and',)
('grew',)
('In',)
('that',)
('first',)
('conversation',)
('my',)
('knees',)
('clicked',)
('and',)
('clacked',)
('And',)
('those',)
('butterflies',)
('flipped',)
('and',)
('flapped',)
('And',)
('as',)
('I',)
('spill',)
('these',)
('simple',)
('rhymes',)
('My',)
('mind',)
('goes',)
('over',)
('time',)
('and',)
('time',)
('I',)
('have',)
('a',)
('crush,',)
('a',)
('little',)
('teenage',)
('crush',)
('I',)
('dont',)
('know',)
('what',)
('to',)
('do,',)
('about',)
('this',)
('lovely',)
('little',)
('crush',)
('Your', 'smile')
('smile', 'makes')
('makes', 'me')
('me', 'smile')
('smile', 'Your')
('Your', 'laugh')
('laugh', 'makes')
('makes', 'me')
('me', 'laugh')
('laugh', 'Your')
('Your', 'eyes')
('eyes', 'are')
('are', 'enchanting')
('enchanting', 'You')
('You', 'make')
('make', 'my')
('my', 'thoughts')
('thoughts', 'seem')
('seem', 'daft')
('daft', 'Since')
('Since', 'the')
('the', 'day')
('day', 'I')
('I', 'first')
('first', 'laid')
('laid', 'eyes')
('eyes', 'on')
('on', 'you')
('you', 'My')
('My', 'feelings')
('feelings', 'grew')
('grew', 'and')
('and', 'grew')
('grew', 'In')
('In', 'that')
('that', 'first')
('first', 'conversation')
('conversation', 'my')
('my', 'knees')
('knees', 'clicked')
('clicked', 'and')
('and', 'clacked')
('clacked', 'And')
('And', 'those')
('those', 'butterflies')
('butterflies', 'flipped')
('flipped', 'and')
('and', 'flapped')
('flapped', 'And')
('And', 'as')
('as', 'I')
('I', 'spill')
('spill', 'these')
('these', 'simple')
('simple', 'rhymes')
('rhymes', 'My')
('My', 'mind')
('mind', 'goes')
('goes', 'over')
('over', 'time')
('time', 'and')
('and', 'time')
('time', 'I')
('I', 'have')
('have', 'a')
('a', 'crush,')
('crush,', 'a')
('a', 'little')
('little', 'teenage')
('teenage', 'crush')
('crush', 'I')
('I', 'dont')
('dont', 'know')
('know', 'what')
('what', 'to')
('to', 'do,')
('do,', 'about')
('about', 'this')
('this', 'lovely')
('lovely', 'little')
('little', 'crush')
('Your', 'smile', 'makes')
('smile', 'makes', 'me')
('makes', 'me', 'smile')
('me', 'smile', 'Your')
('smile', 'Your', 'laugh')
('Your', 'laugh', 'makes')
('laugh', 'makes', 'me')
('makes', 'me', 'laugh')
('me', 'laugh', 'Your')
('laugh', 'Your', 'eyes')
('Your', 'eyes', 'are')
('eyes', 'are', 'enchanting')
('are', 'enchanting', 'You')
('enchanting', 'You', 'make')
('You', 'make', 'my')
('make', 'my', 'thoughts')
('my', 'thoughts', 'seem')
('thoughts', 'seem', 'daft')
('seem', 'daft', 'Since')
('daft', 'Since', 'the')
('Since', 'the', 'day')
('the', 'day', 'I')
('day', 'I', 'first')
('I', 'first', 'laid')
('first', 'laid', 'eyes')
('laid', 'eyes', 'on')
('eyes', 'on', 'you')
('on', 'you', 'My')
('you', 'My', 'feelings')
('My', 'feelings', 'grew')
('feelings', 'grew', 'and')
('grew', 'and', 'grew')
('and', 'grew', 'In')
('grew', 'In', 'that')
('In', 'that', 'first')
('that', 'first', 'conversation')
('first', 'conversation', 'my')
('conversation', 'my', 'knees')
('my', 'knees', 'clicked')
('knees', 'clicked', 'and')
('clicked', 'and', 'clacked')
('and', 'clacked', 'And')
('clacked', 'And', 'those')
('And', 'those', 'butterflies')
('those', 'butterflies', 'flipped')
('butterflies', 'flipped', 'and')
('flipped', 'and', 'flapped')
('and', 'flapped', 'And')
('flapped', 'And', 'as')
('And', 'as', 'I')
('as', 'I', 'spill')
('I', 'spill', 'these')
('spill', 'these', 'simple')
('these', 'simple', 'rhymes')
('simple', 'rhymes', 'My')
('rhymes', 'My', 'mind')
('My', 'mind', 'goes')
('mind', 'goes', 'over')
('goes', 'over', 'time')
('over', 'time', 'and')
('time', 'and', 'time')
('and', 'time', 'I')
('time', 'I', 'have')
('I', 'have', 'a')
('have', 'a', 'crush,')
('a', 'crush,', 'a')
('crush,', 'a', 'little')
('a', 'little', 'teenage')
('little', 'teenage', 'crush')
('teenage', 'crush', 'I')
('crush', 'I', 'dont')
('I', 'dont', 'know')
('dont', 'know', 'what')
('know', 'what', 'to')
('what', 'to', 'do,')
('to', 'do,', 'about')
('do,', 'about', 'this')
('about', 'this', 'lovely')
('this', 'lovely', 'little')
('lovely', 'little', 'crush')
For sentence 1 , trigrams are: 
('Your', 'smile', 'makes')
('smile', 'makes', 'me')
('makes', 'me', 'smile')
('me', 'smile', 'Your')
('smile', 'Your', 'laugh')
('Your', 'laugh', 'makes')
('laugh', 'makes', 'me')
('makes', 'me', 'laugh')
('me', 'laugh', 'Your')
('laugh', 'Your', 'eyes')
('Your', 'eyes', 'are')
('eyes', 'are', 'enchanting')
('are', 'enchanting', 'You')
('enchanting', 'You', 'make')
('You', 'make', 'my')
('make', 'my', 'thoughts')
('my', 'thoughts', 'seem')
('thoughts', 'seem', 'daft')
('seem', 'daft', 'Since')
('daft', 'Since', 'the')
('Since', 'the', 'day')
('the', 'day', 'I')
('day', 'I', 'first')
('I', 'first', 'laid')
('first', 'laid', 'eyes')
('laid', 'eyes', 'on')
('eyes', 'on', 'you')
('on', 'you', 'My')
('you', 'My', 'feelings')
('My', 'feelings', 'grew')
('feelings', 'grew', 'and')
('grew', 'and', 'grew')
('and', 'grew', 'In')
('grew', 'In', 'that')
('In', 'that', 'first')
('that', 'first', 'conversation')
('first', 'conversation', 'my')
('conversation', 'my', 'knees')
('my', 'knees', 'clicked')
('knees', 'clicked', 'and')
('clicked', 'and', 'clacked')
('and', 'clacked', 'And')
('clacked', 'And', 'those')
('And', 'those', 'butterflies')
('those', 'butterflies', 'flipped')
('butterflies', 'flipped', 'and')
('flipped', 'and', 'flapped')
('and', 'flapped', 'And')
('flapped', 'And', 'as')
('And', 'as', 'I')
('as', 'I', 'spill')
('I', 'spill', 'these')
('spill', 'these', 'simple')
('these', 'simple', 'rhymes')
('simple', 'rhymes', 'My')
('rhymes', 'My', 'mind')
('My', 'mind', 'goes')
('mind', 'goes', 'over')
('goes', 'over', 'time')
('over', 'time', 'and')
('time', 'and', 'time')
('and', 'time', 'I')
('time', 'I', 'have')
('I', 'have', 'a')
('have', 'a', 'crush,')
('a', 'crush,', 'a')
('crush,', 'a', 'little')
('a', 'little', 'teenage')
('little', 'teenage', 'crush')
('teenage', 'crush', 'I')
('crush', 'I', 'dont')
('I', 'dont', 'know')
('dont', 'know', 'what')
('know', 'what', 'to')
('what', 'to', 'do,')
('to', 'do,', 'about')
('do,', 'about', 'this')
('about', 'this', 'lovely')
('this', 'lovely', 'little')
('lovely', 'little', 'crush')

"""